version: "3.7"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "4000:4000"
    volumes:
      - /app/node_modules
      - .:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app

  db:
    image: postgres:alpine
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./server/pgdata:/var/lib/postgresql/data
